apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realworld-db
  template:
    metadata:
      labels:
        app: realworld-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "your_secret_password_here"
        - name: POSTGRES_DB
          value: "realworld"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: realworld-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
